version: '3.7'

services:
  db:
    image: mysql:8
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      MYSQL_ROOT_HOST: 172.%.%.%
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_DATABASE: mydb